"use client";
import { useState } from 'react';
import Link from 'next/link';
import { moduleLabels, type DirectoryCompany, type CompanyContact, type CompanyCase, type BusinessModule } from '../lib/company-directory';
import type { PartnershipEvent } from '../lib/partnership-history';
import { useRecordEditor } from '../lib/use-record-editor';
import { useAuth } from '@/store/auth-store';

const contactStatus: Record<CompanyContact['status'], string> = { active: 'ติดต่อได้', resigned: 'ลาออก', transferred: 'ย้ายบริษัท', inactive: 'ไม่ได้ติดต่อ' };
const modules = Object.entries(moduleLabels) as [BusinessModule, string][];
const terms = [{ value: '1', label: 'เทอม 1' }, { value: '2', label: 'เทอม 2' }, { value: 'summer', label: 'Summer' }];

export function CompanyRecord({ company, events, ready, onSave }: { company: DirectoryCompany; events: PartnershipEvent[]; ready: boolean; onSave: (id: string, next: DirectoryCompany) => Promise<boolean> }) {
  const { user } = useAuth();
  const editor = useRecordEditor({ record: company, toDraft: (c: DirectoryCompany) => c, onSave, onClose: () => {} });
  const current = editor.isEditing && editor.draft ? editor.draft : company;
  const [year, setYear] = useState('all'), [module, setModule] = useState('all');
  const years = [...new Set([...events.map(e => e.year), ...current.cases.map(c => c.academicYear)])].sort((a, b) => b - a);
  const visible = events.filter(e => (year === 'all' || String(e.year) === year) && (module === 'all' || e.module === module));
  const cases = [...current.cases].filter(c => (year === 'all' || String(c.academicYear) === year) && (module === 'all' || c.module === module)).sort((a, b) => b.occurredOn.localeCompare(a.occurredOn) || b.recordedAt.localeCompare(a.recordedAt));
  const setContact = (id: string, fields: Partial<CompanyContact>) => editor.updateDraft('contacts', current.contacts.map(c => c.id === id ? { ...c, ...fields } : c));
  const setCase = (id: string, fields: Partial<CompanyCase>) => editor.updateDraft('cases', current.cases.map(c => c.id === id ? { ...c, ...fields } : c));
  return <>
    <section className="panel insight-panel"><div className="panel-heading"><div><h2>{company.name}</h2><p className="panel-caption">ชื่อที่ใช้ในแต่ละโมดูล: {company.aliases.join(' · ')}</p></div>{!editor.isEditing && <button className="secondary-button" disabled={!ready} onClick={editor.startEditing}>แก้ไขผู้ติดต่อและ Case</button>}</div>
      <div className="insight-filters"><label>ปีของประวัติ<select value={year} onChange={e => setYear(e.target.value)}><option value="all">ทุกปี</option>{years.map(y => <option key={y}>{y}</option>)}</select></label><label>งานที่เกี่ยวข้อง<select value={module} onChange={e => setModule(e.target.value)}><option value="all">ทุกโมดูล</option>{modules.map(([m, label]) => <option key={m} value={m}>{label}</option>)}</select></label></div>
      <form onSubmit={editor.saveEditing}>
        <h3>ผู้ประสานงาน ({current.contacts.length})</h3>
        <p className="panel-caption">เมื่อย้ายบริษัทหรือลาออก เปลี่ยนสถานะเพื่อเก็บประวัติเดิม แล้วเพิ่มผู้ติดต่อในบริษัทปลายทาง</p>
        <div className="insight-card-grid">{current.contacts.map((c, index) => <article className="insight-card" key={c.id}>
          {editor.isEditing ? <><h4>ผู้ประสานงาน {index + 1}</h4><div className="insight-form-grid">{([['name', 'ชื่อ'], ['role', 'ตำแหน่ง / บทบาท'], ['phone', 'เบอร์โทร'], ['email', 'อีเมล'], ['lineId', 'LINE']] as const).map(([key, label]) => <label key={key}>{label}ผู้ติดต่อ {index + 1}<input required={key === 'name'} type={key === 'email' ? 'email' : key === 'phone' ? 'tel' : 'text'} maxLength={500} value={c[key]} onChange={e => setContact(c.id, { [key]: e.target.value })} /></label>)}</div><label>สถานะผู้ติดต่อ {index + 1}<select value={c.status} onChange={e => setContact(c.id, { status: e.target.value as CompanyContact['status'] })}>{Object.entries(contactStatus).map(([s, l]) => <option key={s} value={s}>{l}</option>)}</select></label><fieldset className="insight-checkboxes"><legend>รับผิดชอบงาน</legend>{[['general', 'ทั่วไป'], ...modules].map(([m, l]) => <label key={m}><input type="checkbox" checked={c.modules.includes(m as BusinessModule | 'general')} onChange={e => setContact(c.id, { modules: e.target.checked ? [...c.modules, m as BusinessModule | 'general'] : c.modules.filter(v => v !== m) })} />{l}</label>)}</fieldset><button className="text-button" type="button" onClick={() => editor.updateDraft('contacts', current.contacts.filter(p => p.id !== c.id))}>ลบผู้ติดต่อ {index + 1}</button></> : <><h4>{c.name}</h4><small>{c.role} · {contactStatus[c.status]}</small><p>โทร: {c.phone || 'ยังไม่ระบุ'}<br />อีเมล: {c.email || 'ยังไม่ระบุ'}<br />LINE: {c.lineId || 'ยังไม่ระบุ'}</p><small>{c.modules.map(m => m === 'general' ? 'ทั่วไป' : moduleLabels[m]).join(' · ') || 'ยังไม่ระบุงาน'}</small></>}
        </article>)}</div>
        {editor.isEditing && <button className="secondary-button" type="button" onClick={() => editor.updateDraft('contacts', [...current.contacts, { id: crypto.randomUUID(), name: '', role: '', phone: '', email: '', lineId: '', modules: ['general'], status: 'active' }])}>เพิ่มผู้ประสานงาน</button>}
        <h3 className="cap-subheading">Case และบันทึกของบริษัท</h3><p className="panel-caption">เรียงตามวันที่เกิดเหตุ · บันทึกย้อนหลังได้ โดยเก็บวันบันทึกแยกต่างหาก</p>
        <div className="insight-card-grid">{(editor.isEditing ? current.cases : cases).map((c, i) => <article key={c.id} className="insight-card">{editor.isEditing ? <><label>หัวข้อ Case {i + 1}<input required maxLength={500} value={c.title} onChange={e => setCase(c.id, { title: e.target.value })} /></label><label>รายละเอียด Case {i + 1}<textarea rows={3} value={c.detail} onChange={e => setCase(c.id, { detail: e.target.value })} /></label><div className="insight-form-grid"><label>วันที่เกิดเหตุ (ค.ศ.) {i + 1}<input type="date" required value={c.occurredOn} onChange={e => setCase(c.id, { occurredOn: e.target.value })} /></label><label>ปีการศึกษา Case {i + 1}<input type="number" required min={2400} max={3000} value={c.academicYear} onChange={e => setCase(c.id, { academicYear: Number(e.target.value) })} /></label><label>เทอม Case {i + 1}<select value={c.term} onChange={e => setCase(c.id, { term: e.target.value })}>{terms.map(t => <option value={t.value} key={t.value}>{t.label}</option>)}</select></label><label>โมดูล Case {i + 1}<select value={c.module} onChange={e => setCase(c.id, { module: e.target.value as BusinessModule })}>{modules.map(([m, l]) => <option value={m} key={m}>{l}</option>)}</select></label><label>สถานะ Case {i + 1}<select value={c.status} onChange={e => setCase(c.id, { status: e.target.value as CompanyCase['status'] })}><option value="open">ติดตามอยู่</option><option value="closed">ปิดแล้ว</option></select></label></div></> : <><strong>{c.title}</strong><small>{moduleLabels[c.module]} · ปี {c.academicYear}/{c.term} · {c.status === 'open' ? 'ติดตามอยู่' : 'ปิดแล้ว'}</small><p>{c.detail || 'ยังไม่มีรายละเอียด'}</p><small>เกิดเหตุ {c.occurredOn}</small></> }<small>บันทึก {new Date(c.recordedAt).toLocaleDateString('th-TH')} · {c.author}</small></article>)}</div>
        {!cases.length && !editor.isEditing && <p>ยังไม่มี Case ตามตัวกรองนี้</p>}
        {editor.isEditing && <><button className="secondary-button" type="button" onClick={() => editor.updateDraft('cases', [...current.cases, { id: crypto.randomUUID(), title: '', detail: '', academicYear: year === 'all' ? 2569 : Number(year), term: '1', module: module === 'all' ? 'internship' : module as BusinessModule, occurredOn: new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Bangkok' }), recordedAt: new Date().toISOString(), author: user?.username ?? 'เจ้าหน้าที่ทดลอง', status: 'open' }])}>เพิ่ม Case</button><div className="insight-actions"><button type="button" className="secondary-button" disabled={editor.saving} onClick={editor.cancelEditing}>ยกเลิกการแก้ไข</button><button className="primary-button" type="submit" disabled={editor.saving}>บันทึกผู้ติดต่อและ Case</button></div></>}
        {editor.saveError && <p role="alert" className="cap-warning">{editor.saveError}</p>}{editor.saveMessage && <p role="status">{editor.saveMessage}</p>}
      </form>
    </section>
    <section className="panel insight-panel"><h3>ประวัติความร่วมมือข้ามเทอม ({visible.length} รายการ)</h3><p className="panel-caption">รายการจากข้อมูลตัวอย่างปี 2566–2569 · เปิดแต่ละรายการเพื่อตรวจข้อมูลในโมดูลต้นทาง</p><div className="insight-card-grid">{visible.map(e => <article className="insight-card" key={e.id}><small>{moduleLabels[e.module]} · ปี {e.year}/{e.term}</small><h4><Link href={e.href}>{e.title}</Link></h4><p>{e.detail}</p></article>)}</div>{!visible.length && <p>ยังไม่มีประวัติในช่วงที่เลือก</p>}</section>
  </>;
}
