/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Api
         * @description Unauthenticated liveness probe, so the console can tell "backend down"
         *     from "token rejected" without spending a real request.
         */
        get: operations["health_api_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login Api
         * @description Bad credentials and a broken lookup have to stay distinguishable — see
         *     the docstring on login(). Both leave here as AppException subclasses with
         *     their own status, so no try/except is needed.
         */
        post: operations["login_api_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me Api
         * @description Lets the console check a stored token before it renders anything.
         *
         *     Reads the row rather than echoing the token, because the token is signed
         *     once at login: a display name changed since then would otherwise never
         *     reach a client that reloads with a still-valid token.
         */
        get: operations["me_api_api_v1_auth_me_get"];
        /**
         * Update Me Api
         * @description The signed-in user renames itself. The id comes from the token, never
         *     from the body, so this cannot be pointed at somebody else's row.
         */
        put: operations["update_me_api_api_v1_auth_me_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout Api
         * @description Tokens are stateless and self-expiring, so there is nothing to revoke
         *     here — the client dropping the token IS the logout. This endpoint exists so
         *     that stays true from one place, and so a future denylist has a home.
         */
        post: operations["logout_api_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Companies Api */
        get: operations["get_companies_api_api_v1_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Company Api */
        post: operations["create_company_api_api_v1_companies__group_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Company Api */
        put: operations["update_company_api_api_v1_companies__id__put"];
        post?: never;
        /** Delete Company Api */
        delete: operations["delete_company_api_api_v1_companies__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Employees Api */
        get: operations["get_employees_api_api_v1_employees_get"];
        put?: never;
        /** Sync Create Employee Api */
        post: operations["sync_create_employee_api_api_v1_employees_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Employee Api */
        post: operations["approve_employee_api_api_v1_employees__id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Employee Pg Api */
        put: operations["update_employee_pg_api_api_v1_employees__id__put"];
        post?: never;
        /** Decline Employee Api */
        delete: operations["decline_employee_api_api_v1_employees__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Sync Update Employee Api */
        put: operations["sync_update_employee_api_api_v1_employees__id__sync_put"];
        post?: never;
        /** Sync Delete Employee Api */
        delete: operations["sync_delete_employee_api_api_v1_employees__id__sync_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/line/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Line Groups Api */
        get: operations["get_line_groups_api_api_v1_line_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/line/update-information": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Information Api */
        post: operations["update_information_api_api_v1_line_update_information_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Notes Api */
        get: operations["get_notes_api_api_v1_notes_get"];
        put?: never;
        /** Create Note Api */
        post: operations["create_note_api_api_v1_notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Note Api */
        put: operations["update_note_api_api_v1_notes__id__put"];
        post?: never;
        /** Delete Note Api */
        delete: operations["delete_note_api_api_v1_notes__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ContactStatus
         * @enum {string}
         */
        ContactStatus: "pending" | "active" | "resigned" | "transferred" | "inactive";
        /** Company */
        Company: {
            /** Createdat */
            createdAt: string | null;
            /** Updatedat */
            updatedAt: string | null;
            /**
             * Companyth
             * @description ชื่อบริษัทภาษาไทย
             */
            companyTh?: string | null;
            /**
             * Companyen
             * @description ชื่อบริษัทภาษาอังกฤษ
             */
            companyEn?: string | null;
            /**
             * Aliases
             * @description ชื่อเล่นบริษัท
             */
            aliases?: string[] | null;
            /** Id */
            id: number;
            /** Groupid */
            groupId: string | null;
            /** Islinked */
            isLinked: boolean;
        };
        /** CompanyName */
        CompanyName: {
            /**
             * Companyth
             * @description ชื่อบริษัทภาษาไทย
             */
            companyTh?: string | null;
            /**
             * Companyen
             * @description ชื่อบริษัทภาษาอังกฤษ
             */
            companyEn?: string | null;
            /**
             * Aliases
             * @description ชื่อเล่นบริษัท
             */
            aliases?: string[] | null;
        };
        /** Employee */
        Employee: {
            /** Createdat */
            createdAt: string | null;
            /** Updatedat */
            updatedAt: string | null;
            /** @description ความเกี่ยวข้องกับบริษัท */
            relevant?: components["schemas"]["RelevantType"] | null;
            /**
             * Jobtitle
             * @description ตำแหน่งงาน
             */
            jobTitle?: string | null;
            /**
             * Phone
             * @description เบอร์โทรศัพท์
             */
            phone?: string | null;
            /**
             * Email
             * @description อีเมล
             */
            email?: string | null;
            /**
             * Nameth
             * @description ชื่อภาษาไทย
             */
            nameTh?: string | null;
            /**
             * Nameen
             * @description ชื่อภาษาอังกฤษ
             */
            nameEn?: string | null;
            /**
             * Nickname
             * @description ชื่อเล่น
             */
            nickname?: string | null;
            status: components["schemas"]["ContactStatus"];
            /** Companyid */
            companyId: number;
            /** Id */
            id: number;
        };
        /**
         * EmployeeBase
         * @description Schema for creating a new employee.
         */
        EmployeeBase: {
            /** @description ความเกี่ยวข้องกับบริษัท */
            relevant?: components["schemas"]["RelevantType"] | null;
            /**
             * Jobtitle
             * @description ตำแหน่งงาน
             */
            jobTitle?: string | null;
            /**
             * Phone
             * @description เบอร์โทรศัพท์
             */
            phone?: string | null;
            /**
             * Email
             * @description อีเมล
             */
            email?: string | null;
            /**
             * Nameth
             * @description ชื่อภาษาไทย
             */
            nameTh?: string | null;
            /**
             * Nameen
             * @description ชื่อภาษาอังกฤษ
             */
            nameEn?: string | null;
            /**
             * Nickname
             * @description ชื่อเล่น
             */
            nickname?: string | null;
            status: components["schemas"]["ContactStatus"];
            /** Companyid */
            companyId: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LineGroup */
        LineGroup: {
            /**
             * Companyth
             * @description ชื่อบริษัทภาษาไทย
             */
            companyTh?: string | null;
            /**
             * Companyen
             * @description ชื่อบริษัทภาษาอังกฤษ
             */
            companyEn?: string | null;
            /**
             * Aliases
             * @description ชื่อเล่นบริษัท
             */
            aliases?: string[] | null;
            /** Createdat */
            createdAt: string | null;
            /** Updatedat */
            updatedAt: string | null;
            /** Groupid */
            groupId: string;
            /** Displayname */
            displayName: string | null;
            /** Islinked */
            isLinked: boolean;
            /** Companyid */
            companyId: number | null;
            /** Pictureurl */
            pictureUrl: string | null;
        };
        /** ListResponse[Company] */
        ListResponse_Company_: {
            /** Items */
            items: components["schemas"]["Company"][];
            /** Total */
            total?: number | null;
        };
        /** ListResponse[Employee] */
        ListResponse_Employee_: {
            /** Items */
            items: components["schemas"]["Employee"][];
            /** Total */
            total?: number | null;
        };
        /** ListResponse[LineGroup] */
        ListResponse_LineGroup_: {
            /** Items */
            items: components["schemas"]["LineGroup"][];
            /** Total */
            total?: number | null;
        };
        /** ListResponse[Note] */
        ListResponse_Note_: {
            /** Items */
            items: components["schemas"]["Note"][];
            /** Total */
            total?: number | null;
        };
        /** ListResponse[str] */
        ListResponse_str_: {
            /** Items */
            items: string[];
            /** Total */
            total?: number | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * LoginResponse
         * @description accessToken/tokenType at the edge, like every other endpoint — the whole
         *     API speaks camelCase, so auth must not be the one exception the client has
         *     to special-case.
         */
        LoginResponse: {
            /** Accesstoken */
            accessToken: string;
            /**
             * Tokentype
             * @default bearer
             */
            tokenType: string;
            user: components["schemas"]["UserProfile"];
        };
        /**
         * Note
         * @description One row joined with the names the console needs to render it.
         *
         *     company_th / company_en / aliases come from `companies`, person_name /
         *     person_nickname from `employees` — enriched here so the client never has
         *     to stitch three lists together to render one card.
         */
        Note: {
            /**
             * Nameth
             * @description ชื่อภาษาไทย
             */
            nameTh?: string | null;
            /**
             * Nameen
             * @description ชื่อภาษาอังกฤษ
             */
            nameEn?: string | null;
            /**
             * Nickname
             * @description ชื่อเล่น
             */
            nickname?: string | null;
            /**
             * Companyth
             * @description ชื่อบริษัทภาษาไทย
             */
            companyTh?: string | null;
            /**
             * Companyen
             * @description ชื่อบริษัทภาษาอังกฤษ
             */
            companyEn?: string | null;
            /**
             * Aliases
             * @description ชื่อเล่นบริษัท
             */
            aliases?: string[] | null;
            /** Createdat */
            createdAt: string | null;
            /** Updatedat */
            updatedAt: string | null;
            /**
             * Content
             * @description เนื้อหาโน้ต
             */
            content: string;
            /**
             * @description ประเภทของโน้ต
             * @default mou
             */
            type: components["schemas"]["NoteType"];
            /**
             * @description ระดับของโน้ต
             * @default neutral
             */
            sentiment: components["schemas"]["Sentiment"];
            /**
             * @description ที่มาของเรื่อง
             * @default external
             */
            source: components["schemas"]["NoteSource"];
            /** Academicyear */
            academicYear: number;
            /** Term */
            term: 1 | 2 | 3;
            /** Companyid */
            companyId: number;
            /** Employeeid */
            employeeId?: number | null;
            /** Id */
            id: number;
        };
        /**
         * NoteSource
         * @enum {string}
         */
        NoteSource: "internal" | "external";
        /**
         * NoteType
         * @enum {string}
         */
        NoteType: "mou" | "elective" | "internship" | "coop" | "friday" | "person";
        /**
         * NoteCreate
         * @description Body of both writes.
         *
         *     `company_id` is required for every type, because a note is always filed
         *     under a company. `employee_id` is required on top of that when the type is
         *     `person`, and must be absent otherwise — checked in services/note.py, and
         *     again by ck_notes_employee_binding.
         */
        NoteCreate: {
            /**
             * Content
             * @description เนื้อหาโน้ต
             */
            content: string;
            /**
             * @description ประเภทของโน้ต
             * @default mou
             */
            type: components["schemas"]["NoteType"];
            /**
             * @description ระดับของโน้ต
             * @default neutral
             */
            sentiment: components["schemas"]["Sentiment"];
            /**
             * @description ที่มาของเรื่อง
             * @default external
             */
            source: components["schemas"]["NoteSource"];
            /** Academicyear */
            academicYear: number;
            /** Term */
            term: 1 | 2 | 3;
            /** Companyid */
            companyId: number;
            /** Employeeid */
            employeeId?: number | null;
        };
        /**
         * ProfileUpdate
         * @description Body of `PUT /auth/me`. The only thing a user may change about itself.
         */
        ProfileUpdate: {
            /**
             * Displayname
             * @description ชื่อที่ผู้ใช้ตั้งเอง
             */
            displayName?: string | null;
        };
        /**
         * RelevantType
         * @enum {string}
         */
        RelevantType: "mou" | "elective" | "internship" | "coop" | "friday" | "general";
        /**
         * Sentiment
         * @enum {string}
         */
        Sentiment: "positive" | "neutral" | "warning" | "negative";
        /**
         * StatusResponse
         * @description The one shape every write that has nothing to return answers with.
         *     `response_model=dict` told OpenAPI nothing, so the client had to guess.
         */
        StatusResponse: {
            /**
             * Status
             * @default success
             * @constant
             */
            status: "success";
        };
        /**
         * UserProfile
         * @description The signed-in user as the console shows them.
         */
        UserProfile: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /**
             * Displayname
             * @description ชื่อที่ผู้ใช้ตั้งเอง
             */
            displayName?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_me_api_api_v1_auth_me_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_companies_api_api_v1_companies_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse_Company_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_company_api_api_v1_companies__group_id__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyName"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_company_api_api_v1_companies__id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyName"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_company_api_api_v1_companies__id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_employees_api_api_v1_employees_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse_Employee_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_employee_api_api_v1_employees__id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_create_employee_api_api_v1_employees_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeBase"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decline_employee_api_api_v1_employees__id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_employee_pg_api_api_v1_employees__id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeBase"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_update_employee_api_api_v1_employees__id__sync_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeBase"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_delete_employee_api_api_v1_employees__id__sync_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_line_groups_api_api_v1_line_groups_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse_LineGroup_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_information_api_api_v1_line_update_information_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse_str_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_notes_api_api_v1_notes_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse_Note_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_note_api_api_v1_notes_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_note_api_api_v1_notes__id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_note_api_api_v1_notes__id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
